name: scannmay_toolkit
description: A toolkit for students created by KiriRainCat with multiple small functions
publish_to: "none"
version: 0.1.0-alpha

environment:
  sdk: ">=3.1.0-262.2.beta <4.0.0"

dependencies:
  dio: ^5.3.2
  ffi: ^2.0.2
  flutter:
    sdk: flutter
  get: ^4.6.5
  hotkey_manager: ^0.1.8
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  local_notifier: ^0.1.5
  logger: ^2.0.2
  package_info_plus: ^4.1.0
  puppeteer: ^3.3.0
  system_tray: ^2.0.3
  url_launcher: ^6.1.14
  win32: ^4.1.4
  win32_registry: ^1.1.0
  window_manager: ^0.3.5
  windows_single_instance: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  fonts:
    - family: SourceHanSansSC
      fonts:
        - asset: assets/fonts/SourceHanSansSC-Regular.otf
  assets:
    - assets/images/
