import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "zh_CN": {
          "goToJupiter": "前往 Jupiter",
          "dataFetchTimeTooltip": "此时间为数据检索成功的时间",
          "dateFetchSuccess": "数据检索成功",
          "dataFetchInProgress": "数据检索中...",
          "dataFetchFailure": "数据检索失败",
          "pleaseLogin": "请登录~",
          "usernameOrEmail": "用户名/邮箱",
          "password": "密码",
          "login": "登录",
          "updateNotice": "更新提示",
          "updating": "更新中...",
          "updateImmediately": "立即升级",
          "cancel": "取消",
          "jupiterAccountInfo": "Jupiter 账号信息",
          "usernameOrSid": "用户名/SID",
          "confirm": "确认",
          "cookieString": "Cookie 字符串",
          "author": "应用作者: 柒夜雨猫",
          "version": "应用版本",
          "checkUpdate": "检查更新",
          "browserClose": "浏览器关闭",
          "homePage": "主页",
          "class": "科目",
          "notification": "通知",
          "calender": "日历",
          "setting": "设置",
          "about": "关于",
          "re": "重新",
          "fetchDirection": "检索 Directions 信息",
          "newHomework": "新作业提示",
          "remove": "移除",
          "tooltip": "提示",
          "forceFetchData": "强制重新检索数据",
          "clearQueue": "清空队列",
          "deadlineTill": "截止于",
          "daysTillHomework": "日内的作业",
          "incomplete": "未完成",
          "complete": "完成",
          "language": "语言",
          "autoBoot": "开机自启动",
          "dataFetchInterval": "数据检索间隔",
          "changeAccount": "更改账号",
          "saveSettings": "保存设置",
          "change": "更改",
          "noUpdate": "暂无更新",
          "verifiedSaved": "校验成功，已保存",
          "saveSuccess": "保存成功",
          "desc1": "软件的界面语言，如果个别翻译不存在，将会默认使用中文",
          "desc2": "在系统启动后自动打开应用并隐藏至托盘",
          "desc3": "登录 Jupiter 并查看是否有新成绩或作业的时间间隔 (10 min ≤ t ≤ 120 min) *s",
          "desc4": "用于登录 Jupiter ED 进行数据检索的学生账号",
          "info1": "请等待数据检索完成的提示信息，期间请不要重复点击检索数据按钮",
          "info2": "的数据检索完成啦，重新打开详情页以查看信息",
          "info3": "确定要清空消息队列吗？",
          "info4": "已有浏览器正在检索数据",
          "info5": "数据检索已开始，请耐心等待",
          "info6": "*s = 该设置仅在点击保存后生效 | *r = 该设置仅在应用重启后生效",
          "desc7": "用于绕过 Jupiter CF 反爬的 Cookies (请求 header 中的整段 Cookies 字符串)",
          "err1": "字符串不得为空或与旧值相同",
          "err2": "数据检索间隔不合法",
          "err3": "Chromium 自动化浏览器出现上下文异常，作业详情信息获取失败",
          "err4": "远程服务器离线或网络错误",
          "err5": "设置保存异常",
        },
        "en_US": {
          "goToJupiter": "Go to Jupiter",
          "dataFetchTimeTooltip": "This time represents the time for successful data retrieval",
          "dateFetchSuccess": "Data retrieval successful",
          "dataFetchInProgress": "Data retrieval in progress...",
          "dataFetchFailure": "Data retrieval failed",
          "pleaseLogin": "Please log in~",
          "usernameOrEmail": "Username/Email",
          "password": "Password",
          "login": "Login",
          "updateNotice": "Update Notice",
          "updating": "Updating...",
          "updateImmediately": "Update Now",
          "cancel": "Cancel",
          "jupiterAccountInfo": "Jupiter Account Information",
          "usernameOrSid": "Username/SID",
          "confirm": "Confirm",
          "cookieString": "Cookie String",
          "author": "App Author: KiriRainCat (柒夜雨猫)",
          "version": "App Version",
          "checkUpdate": "Check for Updates",
          "browserClose": "Browser Closed",
          "homePage": "Home",
          "class": "Subject",
          "notification": "Notification",
          "calender": "Calendar",
          "setting": "Settings",
          "about": "About",
          "re": "Re-",
          "fetchDirection": "Retrieve Directions Information",
          "newHomework": "New Homework Notification",
          "remove": "Remove",
          "tooltip": "Tooltip",
          "forceFetchData": "Force Data Retrieval",
          "clearQueue": "Clear Notification Queue",
          "deadlineTill": "Deadline by",
          "daysTillHomework": "days for homework",
          "incomplete": "Incomplete",
          "complete": "Complete",
          "language": "Language",
          "autoBoot": "Auto Startup",
          "dataFetchInterval": "Data Retrieval Interval",
          "changeAccount": "Change Account",
          "saveSettings": "Save Settings",
          "change": "Change",
          "noUpdate": "No Update for Now",
          "verifiedSaved": "Verified, being saved",
          "saveSuccess": "Successfully saved",
          "desc1": " Language of the software; if some translations are missing, it will be Chinese",
          "desc2": "Automatically open the application and hide it in the system tray after startup",
          "desc3": "Interval for checking new grades or homework (10 min ≤ t ≤ 120 min) *s",
          "desc4": "Student account used for logging in to Jupiter ED for data retrieval",
          "desc5": "For bypassing Jupiter CF anti-scraping (entire Cookie string in request header)",
          "info1":
              "Please wait for the data retrieval to complete; do not repeatedly click the data retrieval button during this time",
          "info2": "Data retrieval is complete; reopen the details page to view the information",
          "info3": "Are you sure you want to clear the notification queue?",
          "info4": "A browser is already retrieving data",
          "info5": "Data retrieval has started; please be patient",
          "info6":
              "*s = This setting takes effect only after clicking Save\n*r = This setting takes effect only after the application is restarted",
          "err1": "The string must not be empty or the same as the old value",
          "err2": "Invalid data retrieval interval",
          "err3": "Chromium automated browser encountered a context exception and failed to retrieve homework details",
          "err4": "Remote server offline or network issue",
        },
      };
}
